#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Marcel Beck <marcel.beck@mbeck.org>
# @copyright Copyright (c) 2012 Marcel Beck
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

service mcmyadmin stop
port() {
  if [ "$(omv_config_get "//services/mcmyadmin/enable")" == "1" ]; then
    port="$(omv_config_get "//services/mcmyadmin/port")"
    sed -i 's/.*Webserver.Port=.*/Webserver.Port='$port'/' /home/mcmyadmin/McMyAdmin/McMyAdmin.conf
    sed -i "s/':.*\/'/\\':$port\/'/" /var/www/openmediavault/js/omv/module/admin/service/mcmyadmin/Info.js
    sed -i "s/':.*\/'/\\':$port\/'/" /var/www/openmediavault/js/omv/module/admin/service/mcmyadmin/Settings.js
    sed -i "s/':.*\/'/\\':$port\/'/" /var/www/openmediavault/js/omv/module/admin/service/mcmyadmin/WebInterface.js
  fi


}

case "$2" in
  port)
    port
    ;;
  getsettings)
    getsettings
    ;;
  *)
    exit 1
esac
