#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_AS="mcmyadmin"
SERVICE_NAME="mcmyadmin"

case "$1" in
    purge)
        if [ -d "/home/mcmyadmin/McMyAdmin" ]; then
            rm -rf /home/mcmyadmin/McMyAdmin
        fi
        omv_config_delete "//services/${SERVICE_NAME}"
        userdel -r ${RUN_AS}

    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
