#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_AS="mcmyadmin"
RUN_GROUP="mcmyadmin"

SERVICE_NAME="mcmyadmin"

case "$1" in
    configure)

        if ! grep -q "^${RUN_AS}:" /etc/passwd; then
            echo "Adding ${RUN_AS} user..."
            useradd -M -p paxPtk/EBFGAg ${RUN_AS}
        else
            echo "${RUN_AS} user already exists."
        fi
        chown ${RUN_AS}:${RUN_GROUP} -R /home/mcmyadmin

        #insserv -d ${SERVICE_NAME}
        update-rc.d ${SERVICE_NAME} defaults

        if ! omv_config_exists "/config/services/${SERVICE_NAME}"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
	    object="<port>0</port>"
            omv_config_add_element "/config/services" "${SERVICE_NAME}" "${object}" true
        fi

		update-rc.d ${SERVICE_NAME} disable
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0

