#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_AS="mcmyadmin"
RUN_GROUP="mcmyadmin"

SERVICE_NAME="mcmyadmin"

case "$1" in
    configure)

        if ! getent passwd ${RUN_AS} >/dev/null 2>&1; then
            echo "Adding ${RUN_AS} user..."
            useradd -M -p paxPtk/EBFGAg ${RUN_AS}
        else
            echo "${RUN_AS} user already exists."
        fi
        chown ${RUN_AS}:${RUN_GROUP} -R /home/mcmyadmin

        if ! omv_config_exists "/config/services/${SERVICE_NAME}"; then
            echo "Initial configuration."
            object="<enable>0</enable>"
            object="<port>0</port>"
            omv_config_add_element "/config/services" "${SERVICE_NAME}" "${object}" true
        fi
        
        omv_install_fixperms

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0

