#!/bin/sh
#
set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        if [ -d "/home/mcmyadmin/McMyAdmin" ]; then
            rm -rf /home/mcmyadmin/McMyAdmin
        fi

        userdel -r mcmyadmin

    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
